# This is a basic workflow to help you get started with Actions

name: Upload to Google Drive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Show workspace content
        run: |
          pwd
          du -sh *
          
      - name: Upload to Google Drive
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<-EOF
          [remote]
          type = drive
          client_id = 665150049430-qrigmcu7sfn3a0b6j4uo82tedrueullg.apps.googleusercontent.com
          client_secret = dQoefQ99pwoUMkBw-OQPXJ48
          scope = drive
          token = {"access_token":"ya29.a0ARrdaM_TswlvlV6_P2FGqJaXUigMXQqjTkT6AMT5Xxows4YURI-KuOp7FS8bF_7_ncdBBz91QosU5wWGC69rMtcMVpc3TVY3_-ENf2GJPd1zWu13cx6Uj-WaVjNxOHQwRQIGRE7G73M0ZvmlZx2YFq4TiP2M","token_type":"Bearer","refresh_token":"1//04L-lmXLl4ZpkCgYIARAAGAQSNwF-L9IrmdqMakU_nmI42aF1hU_LU1Ynx4ymrMV76M41_7HVZwYhxYAw5Febi-trzHxB9zb_XnA","expiry":"2021-07-04T10:04:33.105474-04:00"}
          EOF
          rclone sync -PLc --exclude='{.*,.*/**}' . remote:deepgd
